<template>
  <v-row justify="center" align="center">
    <v-col cols="12" sm="8" md="6">
      <v-card>
        <v-card-title class="headline">
          トーナメント採点機
        </v-card-title>
          <p>
            <v-btn
              color="primary"
              outlined
              block
              elevation="20"
              to="/Grader1"
            >採点者No.1</v-btn>
          </p>
        <p>
          <v-btn
            color="primary"
            outlined
            block
            elevation="20"
            to="/Grader2"
          >採点者No.2</v-btn>
        </p>
        <p>
          <v-btn
            color="primary"
            outlined
            block
            elevation="20"
            to="/Grader3"
          >採点者No.3</v-btn>
        </p>
        <p>
          <v-btn
            color="primary"
            outlined
            block
            elevation="20"
            to="/Grader4"
          >採点者No.4</v-btn>
        </p>
        <v-card-actions>
        </v-card-actions>
      </v-card>
    </v-col>
  </v-row>
</template>
